name: nza-survey
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - r-base=4.4
  - r-tidyverse
  - r-emmeans
  - r-ggtext
  - r-here
  - r-janitor
  - r-lme4
  - r-matrix
  - r-viridis
  - r-patchwork
  - r-mclust
  - pip
  - pip:
      - snakemake==9.*
